### ISSUE TITLE
What does CoinHive do? is it mining cryptocurrencies?

### ISSUE THREAD

**Issue by jiddisch** [Ismaestro/angular5-example-app#17]
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request

**Comment by Ismaestro** [comment]
Yes!

> Coinhive offers a JavaScript miner for the Monero Blockchain (Why Monero?) that you can embed in your website. Your users run the miner directly in their Browser and mine XMR for you in turn for an ad-free experience, in-game currency or whatever incentives you can come up with.
