### ISSUE TITLE
virus spread

### ISSUE THREAD

**Issue by Krishroger** [Ismaestro/angular5-example-app#18]
#
### Bug Report or Feature Request (mark with an `x`)

- [x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

windows 10
node 6.10.3

npm 3.10.10

### Repro steps.

npm start

### The log given by the failure.

$ npm start

> angular-example-app@5.2.0 start C:\angularjs\angular5-example-app
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-03T12:29:32.210Z
Hash: 678c342888cbe58f6e53
Time: 149419ms
chunk {heroes.module} heroes.module.chunk.js () 55.4 kB  [rendered]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 183 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 1.63 MB [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 2.38 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 184 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 18.6 MB [initial] [rendered]

webpack: Compiled successfully.

### Desired functionality.

npm start of the example angular js 5 project from git repo  https://github.com/Ismaestro/angular5-example-app
After that when you open localhost:4200 it start down download virus file which is prevented by my local Norton antivirus  ( most probably from image file)  Even in

**Comment by pankamilr** [comment]
I think it might not be a virus but bitcoin mining code that is attach in the index.html :-)

**Comment by Krishroger** [comment]
Thanks Even when I  click Demo here in website I can see:  Web attack JSCoin miner website (from Norton)

**Comment by pankamilr** [comment]
True story Bro :-) take a look inside index.html

**Comment by Ismaestro** [comment]
Obviously a JSCoin miner is not a virus but I'm not going to debate about this here. I already deleted the script.
