### ISSUE TITLE
strange output and CORS issues on docker image

### ISSUE THREAD

**Issue by laurencefass** [Ismaestro/angular5-example-app#21]
### Bug Report or Feature Request (mark with an `x`)

- [x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
 

I DONT KNOW HOW TO OBTAIN THIS INFORMATION I HAVE LOGGED INTO DOCKER CONTAINER BUT NG NODE AND NPM ARE NOT ON A KNOWN PATH

### Repro steps.

i followed steps to build and run in docker and the app loads but the loader is running perpetually and also making a circular path on the screen itself....

### The log given by the failure.
Angular library has started with this options:  
Object { config: {…} }
main.6013eb5415a5fdb20c8b.bundle.js:1:1128809
Request for /assets/i18n/en.json took 242 ms.
main.6013eb5415a5fdb20c8b.bundle.js:1:117590
ERROR 
Object { headers: {…}, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown url): 0 Unknown Error", error: error }
main.6013eb5415a5fdb20c8b.bundle.js:1:434568
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nodejs-example-app.herokuapp.com/heroes. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
ERROR 
Object { headers: {…}, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown url): 0 Unknown Error", error: error }

**Comment by Ismaestro** [comment]
Hi @laurencefass !

There is no problem with the app, it's just that Heroku is blocking requests (using CORS) because we reached the limit this month. I'm thinking to pay a monthly fee to have unlimited requests ...

If you go to https://angularexampleapp.com/ and open the console, you will see the error...

BR

**Comment by laurencefass** [comment]
i assume this is for data access. is that correct? how easy would it be to add local data to the app so its self contained. can it be achieved with docker volumes?

perhaps one (small) problem with the app is the orbiting loader?

**Comment by Ismaestro** [comment]
You are right, I'll work on that (both things).

**Comment by laurencefass** [comment]
this is a great starting point for bleeding edge angular development. many thanks. 

will you update here when this is ready to take-off?

**Comment by Ismaestro** [comment]
Yes!! I'll release a new version, tomorrow (If I have time)

**Comment by Ismaestro** [comment]
I've increase the number of hours for the dynos in heroku, so this error is not going to happen anymore.
